### ISSUE TITLE
LR-landing manual QA checklist

### ISSUE THREAD

**Issue by mairead** [epimorphics/hmlr-linked-data#62]
http://hmlr-dev-pres.epimorphics.net/

# Landing specification

Tags: Landing, root

The landing application holds link to SPARQL console and routes to sub applications

## Page

Tags: Landing

The landing page contains descriptive information about the combined land registry applications

- [x] The page loads with appropriate body content
- [x] The page contains multiple links to the applications
- [x] The page contains multiple links to external websites

## Change language

Tags: locale

Users can toggle between English and Welsh language

- [x] Click Cymraeg link in top right
- [x] Displayed body copy will change to Welsh language
- [x] Navigation items will be displayed in Welsh language
- [x] Clicking main navigation title will route user back to home page and language will default to English
- [x] Click English link in top right
- [x] All Displayed text will change to English language

## Header

Tags: navigation

Users can navigate to other sub applications from the landing page

- [x] User can see HM Land registry logo and Header
- [x] 5 primary nav items are visible
- [x] Clicking 'HM Land registry Open Data' will route users back to landing page
- [x] Clicking 'UK House Price Index' will route users to the UKHPI app
- [x] Clicking 'Price Paid Data' will route users to the PPD app
- [x] Clicking 'Standard-reports' will route users to the standard reports app
- [x] Clicking 'SPARQL query' will route users to the console query page
- [x] Clicking logo in top left navigates users to the Gov.uk site relating to the land registry
- [x] When the browser width is reduced the navigation layout will change

## Navigation

Tags: navigation

- [x] Clicking 'UK House Price Index' will route users to the UKHPI app
- [x] The primary navigation displays different options relating to UKHPI
- [x] All other sub-applications retain the navigation structure of the landing page

**Comment by tomguilbert** [comment]
There is something wrong with the language localisation in the Qonsole tab. See https://hmlr-dev-pres.epimorphics.net/app/qonsole?lang=en which provides the page with Welsh headers and https://hmlr-dev-pres.epimorphics.net/app/qonsole?lang=cy which provides them in English! @jonrandahl

**Comment by jonrandahl** [comment]
Just putting this here so it's not lost:

> language on LIVE doesn’t change for anything BUT the landing page and Qonsole and UKHPI - but both PPD and Standard Reports do not translate

This is in the code as there are NO translation files for PPD or SR

**Comment by tomguilbert** [comment]
That isn't actually what I meant @jonrandahl 

If you go to the landing page and switch to Welsh, then click on the link to Qonsole, it initially loads with the headers in English despite the URL being `https://hmlr-dev-pres.epimorphics.net/app/qonsole?lang=cy`. If you then refresh the page it reloads with the headers in Welsh. This is in fact the same behaviour as in Production so not a regression, but it is a bit weird. Happy to close as I don't think we should spend time on this if it is currently that way in prod anyway.

Closing this ticket as everything is as in Prod now.
