### ISSUE TITLE
PPD results manual QA checklist

### ISSUE THREAD

**Issue by joescottdave** [epimorphics/hmlr-linked-data#63]
# Price Paid Data Search results

Tags: search, PPD, Price paid data

The Price paid data search results view

## Deselect search queries

Tags: results

- [ ] Type "Rose Cottage" into the "Building name or number" field
- [ ] Type "Plymouth" into the "Town or city" field
- [ ] Clicking show results will route User to the search results page
- [ ] Summary will display '21 transactions'
- [ ] Clicking the cross icon next to 'Plymouth' will remove the search query parameter
- [ ] Results page will re-render with new search parameters applied
- [ ] Summary will display '9873 matching transactions'

## Change settings

Tags: results

- [ ] Type "Rose Cottage" into the "Building name or number" field
- [ ] Clicking show results will route User to the search results page
- [ ] Clicking 'change search settings' will router User to search form
- [ ] Prefilled value "Rose Cottage" visible in the "Building name or number" field

## Download data

Tags: results

- [ ] Type "Rose Cottage" into the "Building name or number" field
- [ ] Clicking show results will route User to the search results page
- [ ] Clicking 'download data' will router User to the download page
- [ ] Clicking 'get selected results as CSV' will prompt a file download of type CSV
- [ ] Clicking 'get selected results as Turtle' will route User to generated TTL file
- [ ] Clicking 'view SPARQL query' will route User to SPARQL query view with pre-populated search values
- [ ] Clicking 'Back to results' will return you to the results page

## Share

Tags: results

- [ ] Clicking 'share view' will open a modal dialogue prompting a Twitter link
- [ ] The Users can close the modal dialogue by clicking the close cross

## Results summary number displayed

Tags: results

- [ ] Summary will display 'Showing 100 transactions'
- [ ] Clicking 'show a sample of at most 1000 results' will requery the search with new parameters
- [ ] Results page will re-render with new search parameters applied
- [ ] Summary will display 'Showing 1000 transactions'
- [ ] Clicking 'show all results' will requery the search with new parameters
- [ ] Results page will re-render with new search parameters applied
- [ ] Summary will display 'Current selection: show all results'

## Results list item

Tags: results

- [ ] A result item has a postal address as title
- [ ] A result item has a list of transaction History with at least one or more item
- [ ] Clicking the transaction history external link will route User to the Elda API populated with property transaction data
- [ ] A result item has a list of address values

## Results list query within

Tags: results

- [ ] Reset the form
- [ ] Type "Rose Cottage" into the "Building name or number" field
- [ ] Type "Devon" into the "County" field
- [ ] Clicking show results will route User to the search results page
- [ ] Summary will display 'from 460 matching transactions'
- [ ] Summary will display '45 properties'
- [ ] First Result item displays 'Rose Cottage, High Street, Sidmouth, EX10 0DU'
- [ ] Clicking the magnifiying glass icon adjacent to 'East Devon' will requery the search
- [ ] Search summary now displays 'district matches 'EAST DEVON'
- [ ] Summary will display '81 transactions'
- [ ] Summary will display '50 properties'
- [ ] First Result item displays 'Briar Rose Cottage, Lyme Regis, DT7 3RN'

**Comment by joescottdave** [comment]
SPARQL query redirect is broken (related to proxy configuration discussion on #52 )

The matching transactions snippet of text is not rendering a number

**Comment by tomguilbert** [comment]
@jonrandahl looks like "Clicking the cross icon next to 'Plymouth' will remove the search query parameter" has a broken route

**Comment by jonrandahl** [comment]
This seems to be a combination of the new infrastructure alongside changes that were made for the configuration of the individual apps by @andrew-pickin-epi and myself while looking at the proxy setup. 

I found a [Rails support ticket from 2020](https://github.com/rails/rails/issues/40237) which references this exact situation and, as noted in Slack, [it seems we've been here before](https://github.com/rails/rails/issues/40237#issuecomment-735268395) ... 

I've implemented the recommended change locally and tested inside a docker image (as per how the production instances are) and this seems to work.

Will update when pushed up for approval.

**Comment by tomguilbert** [comment]
I have tested this and everything works correctly now. The only outstanding item is that the number of results doesn't match production, as reported in #64 - will await response to that before deciding if this is done.

**Comment by tomguilbert** [comment]
Confirmed that something is wrong with the number of results so putting this back into in progress. Will await resolution of #123

**Comment by tomguilbert** [comment]
#123 not a bug and have retested these tested and they work properly
