### ISSUE TITLE
PPD search manual QA checklist

### ISSUE THREAD

**Issue by joescottdave** [epimorphics/hmlr-linked-data#64]
http://hmlr-dev-pres.epimorphics.net/app/ppd/

# Price Paid Data

Tags: PPD, price paid data

The price paid data search form

## Building search

Tags: Search

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '9873 matching transactions')
- [x] Summary will display the same number of properties as production (currently '62 properties')
- [x] First result item address displays as 'Rose Cottage, North Road, Wells, BA5 1LA'
- [x] Reset the form

## Street search

Tags: Search

- [x] Type "Harbour Road" into the "Street" field
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '2192 matching transactions')
- [x] First result item address displays as '73 Harbour Road, Bradford, BD6 3RG'
- [x] Reset the form

## Town search

Tags: Search

- [x] Type "Plymouth" into the "Town or city" field
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '10000 or more matching transactions')
- [x] Summary will display the same number of properties as production (currently '60 properties')
- [x] First result item address displays as '25 Trinity Street, Plymouth, PL1 3FT'
- [x] Reset the form

## District search

Tags: Search

- [x] Type "City of Westminster" into the "District" field
- [x] Select `at most 1000` results
- [x] Clicking show results will route User to the search results page
- [X] Summary will display the same number of transactions as production (currently  '10000 or more matching transactions')
- [x] Summary will display the same number of properties as production (currently '643 properties')
- [x] First result item address display same as production (currently _51 Nottingham Terrace, London, NW1 4QD_)
- [x] Reset the form

## County search

Tags: Search

- [x] Type "Devon" into the "County" field
- [x] Select 'at most 100' results
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently 'from 10000 or more matching transactions')
- [x] Summary will display the same number of properties as production (currently '57 properties')
- [x] First result item address displays as 'The Summerhouse, Lyme Regis, DT7 3XU'
- [x] Reset the form

## Locality search

Tags: Search

- [x] Type "Thurloxton" into the "Locality" field
- [x] Clicking show results will route User to the search results page
- [x] Summary will display '71 transactions'
- [x] First result item address displays as 'Greenway Farm House, Taunton, TA2 8RF'
- [x] Reset the form

## Postcode search

Tags: Search

- [x] Type "PL6" into the "Postcode" field
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '10000 or more matching transactions')
- [x] Summary will display the same number of properties as production ('61 properties')
- [x] First result item address displays as '1 Moreton Avenue, Plymouth, PL6 5AZ'
- [x] Reset the form

## Property type filter

Tags: Search

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Deselect 'detached' and 'semi-detached' from the 'Property Type' checkbox list
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '1658 matching transactions')
- [x] First result item address displays as 'Rose Cottage, Wells Road, Bath, BA2 9AY'
- [x] Reset the form

## New build filter

Tags: Search

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Deselect 'not new-build' from the 'New build?' checkbox list
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '150 matching transactions')
- [x] First result item address displays as 'Rose Cottage, Fore Street, Warminster, BA12 0RQ'
- [x] Reset the form

## Estate type filter

Tags: Search

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Deselect 'leasehold' from the 'Estate Type' checkbox list
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '9731 matching transactions')
- [x] First result item address displays as 'Rose Cottage, North Road, Wells, BA5 1LA'
- [x] Reset the form

## Transaction category filter

Tags: Search

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Deselect 'standard' from the 'Transaction category' checkbox list
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '239 matching transactions')
- [x] First result item address displays as 'Rose Cottage, Gilson Road, Birmingham, B46 1LN'
- [x] Reset the form

## Price range filter

Tags: Search

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Input '0' to the 'Minimum price' field
- [x] Input '200000' to the 'Maximum price' field
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '4753 matching transactions')
- [x] First result item address displays as 'Rose Cottage, Malt Mill Lane, Halesowen, B62 8JE'
- [x] Reset the form

## Date range filter

Tags: Search

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Select '22/11/2020' in the 'earliest' field
- [x] Select '22/11/2021' in the 'latest' field
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '273 matching transactions')
- [x] First result item address displays as 'Rose Cottage, Malt Mill Lane, Halesowen, B62 8JE'
- [x] Reset the form

## Small date range

Tags: Search

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Select '19/11/2021' in the 'earliest' field
- [x] Select '22/11/2021' in the 'latest' field
- [x] Clicking show results will route User to the search results page
- [x] Summary will display '0 transactions'
- [x] Reset the form

## Invalid date range (earliest date occurs after latest date)

Tags: Search

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Select '22/11/2021' in the 'earliest' field
- [x] Select '22/11/2020' in the 'latest' field
- [x] Clicking show results will route User to the search results page
- [x] Summary will display '0 transactions'
- [x] Reset the form

## Limit results to 1000

Tags: Search

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Select 'at most 1000' from the 'How many results?' radio list
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '9873 matching transactions')
- [x] Summary will display the same number of properties as production ('570 properties')
- [x] First result item address displays as 'Rose Cottage, Lower Gustard Wood, St Albans, AL4 8RU'
- [x] Reset the form

## No Limit results

Tags: Search

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Select 'all' from the 'How many results?' radio list
- [x] Clicking show results will route User to the search results page
- [x] Summary will display the same number of transactions as production (currently '9873 matching transactions')
- [x] Summary will display the same number of properties as production ('5887 properties')
- [x] A warning is visible with the phrase 'We have limited this page to 5000 results'
- [x] First result item address displays as 'Rose Cottage, Lower Gustard Wood, St Albans, AL4 8RU'
- [x] Reset the form

## Large queries

Tags: Search

- [ ] Type "Birmingham" into the "Town or city" field
- [ ] Select 'all' from the 'How many results?' radio list
- [ ] Clicking show results will route User to the search results page after '1m 40s'
- [ ] Summary will display 'Found 388822 transactions'
- [ ] Summary will display the same number of properties as production ('for 227036 properties')
- [ ] A warning is visible with the phrase 'We have limited this page to 5000 results'
- [ ] First result item address displays as 'Apartment 2109, 10 Holloway Circus Queensway, Birmingham, B1 1BA'
- [ ] Reset the form

## Help

- [x] Clicking 'Help' button will open a modal dialogue window with Help text
- [x] The User can link to troubleshooting guidance from here
- [x] The User can close the modal dialogue by clicking the cross icon

## Reset form

- [x] Type "Rose Cottage" into the "Building name or number" field
- [x] Type "Thurloxton" into the "Locality" field
- [x] Clicking 'reset the form' will remove all previously entered input values

**Comment by tomguilbert** [comment]
I have run through all this and, bar [one small presentational bug](https://github.com/epimorphics/hmlr-linked-data/issues/122), everything works. However:

1. The transaction and property numbers returned, and the top results, don't match production in most cases. I presume this is because the data in dev is different to production but making a note here. Is this true and if so do we need to check more thoroughly with a matching dataset, or are we content to move to testing with HMLR?
2. The section **Large queries** does not work as expected in this script. After about 1m 40s you get the following:

![Image](https://github.com/epimorphics/hmlr-linked-data/assets/97290791/c9078920-18d9-4722-88e0-7a69e137be43)

Is this as expected or do we need to test again on full production-scale infrastructure as we said we would for SR [here](https://github.com/epimorphics/hmlr-ansible-deployment/issues/165)?

@der I'm guessing you are the person who will know the answer to these questions :)

**Comment by tomguilbert** [comment]
OK thanks Dave - I will make a separate ticket for this

**Comment by tomguilbert** [comment]
>The transaction and property numbers returned, and the top results, don't match production in most cases. I presume this is because the data in dev is different to production but making a note here. Is this true and if so do we need to check more thoroughly with a matching dataset, or are we content to move to testing with HMLR?

Not a bug - user needs to 'show all results' then gets the numbers to match. See #123

**Comment by tomguilbert** [comment]
I think everything here has passed now, except for the large queries, for which there is a separate ticket. So I am closing this.
