### ISSUE TITLE
standard-reports manual QA checklist

### ISSUE THREAD

**Issue by joescottdave** [epimorphics/hmlr-linked-data#65]
http://hmlr-dev-pres.epimorphics.net/app/standard-reports

# Standard reports

Tags: standard, report

## Landing page

Tags: landing

- [x] User can read description of report application
- [x] User can access link to report building tool

## Select a report type - step 1

Tags: standard, report

- [x] The User is currently viewing 'step 1 of 7'
- [x] Select a link to create a report
- [x] A User can click to view expanded sections of the page
- [x] A User can select radio inputs
- [x] A User cannot progress until a selection is made
- [x] Select 'Average prices and volumes'
- [x] Click button to advance to 'Next' screen

## Geographical - country - step 2

Tags: standard, report, location

- [x] The User is currently viewing 'step 2 of 7'
- [x] A User cannot progress until a selection is made
- [x] Select 'country'
- [x] Click button to advance to 'Next' screen
- [x] The User is currently viewing 'step 3 of 7'
- [x] The only option is prefilled for 'England and Wales'
- [x] Click button to advance to 'Next' screen
- [x] The User is currently viewing 'step 4 of 7'
- [x] The User can see 6 options for location specification
- [x] Select 'Don't aggregate, just show the total'
- [x] Click button to advance to 'Next' screen
- [x] Advance to step 5

## Geographical - region

Tags: standard, report, location

- [x] Repeat step 1
- [x] The User is currently viewing 'step 2 of 7'
- [x] Select 'region'
- [x] Click button to advance to 'Next' screen
- [x] The User is currently viewing 'step 3 of 7'
- [x] The User can select region from a list of options
- [x] The User can select a region from a map view
- [x] The User can zoom in and out of the map
- [x] Hover over a highlighted area will display region name
- [x] Clicking on a highlighted area will select that option from the list
- [x] Click button to advance to 'Next' screen
- [x] The User is currently viewing 'step 4 of 7'
- [x] The User can see 6 options for location specification
- [x] Select 'Don't aggregate, just show the total'
- [x] Click button to advance to 'Next' screen
- [x] Advance to step 5

## Geographical - county

Tags: standard, report, location

- [x] Repeat step 1
- [x] The User is currently viewing 'step 2 of 7'
- [x] select 'County, Unitary Authority or Greater London'
- [x] Click button to advance to 'Next' screen
- [x] The User is currently viewing 'step 3 of 7'
- [x] The User can input text and see matching locations in a dropdown menu
- [x] The User can select a location from a map view
- [x] The User can zoom in and out of the map
- [x] Hover over a highlighted area will display a location name
- [x] Clicking on a highlighted area will prefill the input field with the location name
- [x] The User is currently viewing 'step 4 of 7'
- [x] The User can see 5 options for location specification
- [x] Select 'Don't aggregate, just show the total'
- [x] Click button to advance to 'Next' screen
- [x] Advance to step 5

## Geographical - district

Tags: standard, report, location

- [x] Repeat step 1
- [x] The User is currently viewing 'step 2 of 7'
- [x] select 'District or London Borough'
- [x] Click button to advance to 'Next' screen
- [x] The User is currently viewing 'step 3 of 7'
- [x] The User can input text and see matching locations in a dropdown menu
- [x] Input "Southwark" to the input field
- [x] Click button to advance to 'Next' screen
- [x] The User is currently viewing 'step 4 of 7'
- [x] The only option is prefilled for 'Don't aggregate, just show the total'
- [x] Click button to advance to 'Next' screen
- [x] Advance to step 5

## Geographical - postcode area

Tags: standard, report, location

- [x] Repeat step 1
- [x] The User is currently viewing 'step 2 of 7'
- [x] select 'Postcode area (e.g. ‘GL’)'
- [x] Click button to advance to 'Next' screen
- [x] The User is currently viewing 'step 3 of 7'
- [x] The User can input text
- [x] Input "BS" to the input field
- [x] The User is currently viewing 'step 4 of 7'
- [x] The User can see 3 options for location specification
- [x] Select 'Don't aggregate, just show the total'
- [x] Click button to advance to 'Next' screen
- [x] Advance to step 5

## Geographical - postcode district

Tags: standard, report, location

- [x] Repeat step 1
- [x] The User is currently viewing 'step 2 of 7'
- [x] select 'Postcode district (e.g. ‘GL1’)'
- [x] Click button to advance to 'Next' screen
- [x] The User is currently viewing 'step 3 of 7'
- [x] The User can input text
- [x] Input "BS49" to the input field
- [x] The User is currently viewing 'step 4 of 7'
- [x] The User can see 2 options for location specification
- [x] Select 'Don't aggregate, just show the total'
- [x] Click button to advance to 'Next' screen
- [x] Advance to step 5

## Geographical - postcode sector

Tags: standard, report, location

- [x] Repeat step 1
- [x] The User is currently viewing 'step 2 of 7'
- [x] select 'Postcode sector (e.g. ‘GL1 2’)'
- [x] Click button to advance to 'Next' screen
- [x] The User is currently viewing 'step 3 of 7'
- [x] The User can input text
- [x] Input "BS49 2" to the input field
- [x] The User is currently viewing 'step 4 of 7'
- [x] The only option is prefilled for 'Don't aggregate, just show the total'
- [x] Click button to advance to 'Next' screen
- [x] Advance to step 5

## time period - step 5

Tags: standard, report, time

- [x] The User is currently viewing 'step 5 of 7'
- [x] The User can select a number of time periods to generate a report from
- [x] Select 'Year to date'
- [x] Click button to advance to 'Next' screen

## Visible dates - step 5

Tags: standard, report, time

- [x] Repeat step 1
- [x] Repeat Geographical - country - step 2
- [x] The User is currently viewing 'step 5 of 7'
- [x] The User can see the current year and select 'current year to date'
- [x] The User can only select months in the current year up until the 'previous month'
- [x] The User can see the previous year and select 'previous year all year'
- [x] The User can click more dates to expand a greater selection of options
- [x] The User can see all years dating back to 1995
- [x] The User can select any month within a full year

## additional options - step 6

Tags: standard, report

- [x] The User is currently viewing 'step 6 of 7'
- [x] The User can select different property types
- [x] A User cannot progress until a selection is made
- [x] Select 'Both old and new properties'

## summary display - step 7

Tags: standard, report

- [x] The User is currently viewing 'step 7 of 7'
- [x] The User can read the parameters they have chosen in previous steps
- [x] Select "change..." adjacent 'report type is average prices and volumes'
- [x] The User is routed to step 1
- [x] Select 'Banded prices'
- [x] Click button to advance to 'Next' screen
- [x] The User is routed back to step 7

## report generation

Tags: standard, report

- [x] Repeat step 1
- [x] Repeat Geographical - country - step 2
- [x] The User is currently viewing 'step 5 of 7'
- [x] Select 'Year to date'
- [x] Select 'Latest quarter for which data is available'
- [x] Select 'Latest month for which data is available'
- [x] Select '2021 to date'
- [x] Select '2020 all year'
- [x] Click button to advance to 'Next' screen
- [x] Repeat step 6
- [x] Click 'Generate report' button
- [x] Whilst generating the User will see 'in progress, estimated complete in' with a given timeframe.
- [x] Before generation starts The User may also see 'waiting to start. Position in queue:' with a queue position
- [x] The User can click to download as XLS format
- [x] The User can click to download as CSV format
- [x] The User can click to return to the first step

**Comment by joescottdave** [comment]
Advancing beyond the final step of "Geographical - country - step 2" results in an error message "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

**Comment by joescottdave** [comment]
Steps for "Geographical - region" map is not loading.  404 on resource '/region-geatures.json' (possibly not aliasing properly?)

**Comment by tomguilbert** [comment]
Both of the issues reported by Joseph above are now resolved

**Comment by tomguilbert** [comment]
Can't complete step `The User can only select months in the current year up until the 'previous month'` under Visible dates - step 5 because the available months stop at Jul 2022 - is that when the test data in the service runs out @jonrandahl?

**Comment by der** [comment]
The data in dev is certainly out of date by several months, could well be as old as July 2022.

**Comment by tomguilbert** [comment]
OK thanks @der - I think that clears that test then.

**Comment by tomguilbert** [comment]
Tests failed at the point of creating new files:


![Image](https://user-images.githubusercontent.com/97290791/215528322-2ae97f07-4a75-4220-87a0-f554503b1202.png)

So have left the penultimate checkbox and the one before (antepenultimate?) unchecked.

**Comment by tomguilbert** [comment]
I've rerun the tests on here, and thought I had adjusted things (avoiding selecting 2023) so that they would run successfully, but to no avail. See screenshot, where it hung for some time (the URL is https://hmlr-dev-pres.epimorphics.net/app/standard-reports/download-report?utf8=%E2%9C%93&report=avgPrice&areaType=country&area=EW&aggregate=none&period%5B%5D=ytd&period%5B%5D=latest_q&period%5B%5D=latest_m&period%5B%5D=2022&period%5B%5D=2021&age=any)

<img width="533" alt="image" src="https://github.com/epimorphics/hmlr-linked-data/assets/97290791/2a943d1c-a99f-4d25-9017-e5d061551a35">

I'll run some test reports that actually have data to see if it is data related as I suspect or something more fundamental.

**Comment by tomguilbert** [comment]
I'm now being told that my (much smaller) reports are 5th, 6th and 7th in the queue, presumably behind the 5 shown in the screenshot on the previous comment. The URL for these is https://hmlr-dev-pres.epimorphics.net/app/standard-reports/download-report?utf8=%E2%9C%93&report=avgPrice&areaType=pcDistrict&area=BA2&aggregate=none&period%5B%5D=2022-01&period%5B%5D=2022-02&period%5B%5D=2022-03&age=any

**Comment by tomguilbert** [comment]
Today I ran a series of reports, getting increasingly larger, one at a time. All the different sizes of geography worked fine except for country. I even tried running several small ones at the same time and these queued up nicely and output after a short wait.

For the country level reported I only requested the data for January this year, so as small a request as possible. This ran for a few hours then the screen came back as follows:

![Image](https://github.com/epimorphics/hmlr-linked-data/assets/97290791/d01d95d5-c1a9-4f53-81a5-96b342aff667)
