### ISSUE TITLE
UKHPI data comparison manual QA checklist

### ISSUE THREAD

**Issue by joescottdave** [epimorphics/hmlr-linked-data#66]
http://hmlr-dev-pres.epimorphics.net/app/ukhpi

# UKHPI data comparison

Tags: data, results, compare

The comparison table allows you to compare data from up to 5 locations with the same set of parameters

## Compare with another location tab

Tags: data, results, compare

- [x] Default query is set to 'United Kingdom' and 'October 2020 to October 2021'
- [x] Click to expand the view of 'Average price by type of property'
- [x] Clicking 'Compare with location' displays a location selection control
- [x] Click 'select another location'
- [x] Type 'London' and press enter
- [x] The User is routed to the 'compare locations' page with the query prepopulated
- [x] A data table is visible showing data for the locations and date range specified

## Compare locations view - query parameters

Tags: data, results, compare

- [x] A User can select Data type options from the Compare select menu
- [x] The table of date will refresh based on new query parameters added
- [x] A User can select the type of query option from the type select menu
- [x] The table of date will refresh based on new query parameters added
- [x] A User can specify a date range from the Date range edit control
- [x] The table of date will refresh based on new query parameters added

## Compare locations view - location parameters

- [x] A User can select up to 5 locations using the location edit control
- [x] A new column is added for each location specified
- [x] Clicking the 'CSV/spreadsheet' button will prompt a CSV file download
- [x] Clicking the 'JSON' button will prompt a JSON download
- [x] Clicking 'print this table' will open a new browser window showing a printable view of data
- [x] The print control will open

**Comment by tomguilbert** [comment]
(1st bullet) - Default query is set to 'United Kingdom' and 'May 2022 to May 2023' but assume this is correct given the change in the underlying data.

All other tests passed so closing
