### ISSUE TITLE
UKHPI data display manual QA checklist

### ISSUE THREAD

**Issue by joescottdave** [epimorphics/hmlr-linked-data#67]
http://hmlr-dev-pres.epimorphics.net/app/ukhpi

# UKHPI data display

Tags: UKHPI

## Query results default parameters

Tags: data, results

- [x] Application will default to display the query end period 'the latest month for which data is available'
- [x] Application will default to display the query start period '12 months prior' to the 'end period'
- [x] Application will default to show location of 'United Kingdom'

## Chart sections - type of property

Tags: data, results

- [x] User can view section heading for 'Type of Property' and click quick link at top of page to anchor to section
- [x] User can expand a section to view a chart of 'Average price type of property'
- [x] User can expand a section to view a chart of 'Percentage change (yearly) by type of property'
- [x] User can expand a section to view a chart of 'Percentage change (monthly) by type of property'
- [x] User can expand a section to view a chart of 'House price index by type of property'
- [x] User can expand a section to view a chart of 'Sales volume by type of property'

## Chart sections - Buyer status

Tags: data, results

- [x] User can view section heading for 'Buyer status' and click quick link at top of page to anchor to section
- [x] User can expand a section to view a chart of 'Average price by buyer status'
- [x] User can expand a section to view a chart of 'Percentage change (yearly) by buyer status'
- [x] User can expand a section to view a chart of 'Percentage change (monthly) by buyer status'
- [x] User can expand a section to view a chart of 'House price index by buyer status'

## Chart sections - Funding status

Tags: data, results

- [x] User can view section heading for 'Funding status' and click quick link at top of page to anchor to section
- [x] User can expand a section to view a chart of 'Average price by funding status'
- [x] User can expand a section to view a chart of 'Percentage change (yearly) by funding status'
- [x] User can expand a section to view a chart of 'Percentage change (monthly) by funding status'
- [x] User can expand a section to view a chart of 'House price index by funding status'
- [x] User can expand a section to view a chart of 'Sales volume by funding status'

## Chart sections - Property status

Tags: data, results

- [x] User can view section heading for 'Property status' and click quick link at top of page to anchor to section
- [x] User can expand a section to view a chart of 'Average price by property status'
- [x] User can expand a section to view a chart of 'Percentage change (yearly) by property status'
- [x] User can expand a section to view a chart of 'Percentage change (monthly) by property status'
- [x] User can expand a section to view a chart of 'House price index by property status'
- [x] User can expand a section to view a chart of 'Sales volume by property status'

## View data graph tab

Tags: data, results

- [x] User can expand first item in first section to view a chart of 'Average price type of property'
- [x] User can see tabbed navigation which defaults to 'See data graph' tab content
- [x] User can see a line graph of data
- [x] The line graph defaults to showing 'All property types'
- [x] The User can select property type checkboxes to add data points to line graph
- [x] The User can click the magnifying glass icon to view the line graph in a modal dialogue
- [x] The User can click on the chart to view the line graph in a modal dialogue

## View data table tab

Tags: data, results

- [x] Set query to 'United Kingdom' and 'October 2020 to October 2021'
- [x] Click to expand the view of 'Average price by type of property'
- [x] Clicking 'See data table' tab shows tabular data of query
- [x] Table row display for 'Date' 'Oct 2020' value is '£243.821'
- [x] The User can select property type checkboxes to add data columns to the table
- [x] Clicking 'print this table' will open a new browser window showing a printable view of data
- [x] The print control will open

## Download this data tab

Tags: data, results

- [x] Set query to 'United Kingdom' and 'October 2020 to October 2021'
- [x] Click to expand the view of 'Average price by type of property'
- [x] Clicking 'Download this data' tab shows a selection of download links to view data exports
- [x] Clicking the 'download CSV/spreadsheet' button will prompt a CSV file download
- [x] Clicking the 'download JSON' button will prompt a JSON download
- [x] Clicking the 'try the SPARQL query' link will open the SPARQL console with the query pre-populated

**Comment by tomguilbert** [comment]
Table row display for 'Date' 'Oct 2020' value is '£243.821' in 7th section the value is different, but I take it that this is due to data changes since this script was written. Data matches production on comparison (£243,575).

Calling this one done
