### ISSUE TITLE
UKHPI data query manual QA checklist

### ISSUE THREAD

**Issue by joescottdave** [epimorphics/hmlr-linked-data#68]
http://hmlr-dev-pres.epimorphics.net/app/ukhpi

# UKHPI application

Tags: UKHPI

The UK house price index displaying value of house sales

## Landing page

Tags: Landing, root

- [x] The page loads with appropriate body content
- [x] The page contains multiple links to the applications
- [x] The page contains multiple links to external websites

## Change language

Tags: locale

Users can toggle between English and Welsh language

- [x] Click Cymraeg link in top right
- [x] Displayed body copy will change to Welsh language
- [x] Navigation items will be displayed in Welsh language
- [x] Clicking main navigation title will route user back to home page and language will default to English
- [x] Click English link in top right
- [x] All Displayed text will change to English language

## Header and primary navigation

Tags: navigation

- [x] A custom header is visible which differs from the other applications
- [x] The UKHPI logo is shown in the top left
- [x] Clicking 'browse' will route users to the data display
- [x] Clicking 'compare locations' will route users to the comparison table view
- [x] Clicking 'SPARQL query' will route users to a SPARQL console view
- [x] Clicking 'user guide' will route users to a user guide view
- [x] Clicking 'about UKHPI' will route users to a page of descriptive information
- [x] Clicking 'change history' will router users to a page of historic change information

## Location map view

Tags: query, filter

- [x] Clicking the location edit button will open a modal dialogue with map view
- [x] A User can zoom in and zoom out of the map with the '+' and '-' buttons
- [x] A user can close the modal dialogue by clicking the cross icon

## Filter Location by keyword - select from list

Tags: query, filter

- [x] Clicking the location edit button will open a modal dialogue with map view
- [x] Typing 'Bi' will prompt a select menu of location options to appear
- [x] A user can select an option from the select menu and click confirm button
- [x] The modal dialogue will close and the location query parameter will be set
- [x] Clicking the location edit button will open a modal dialogue with map view

## Filter Location by keyword - type location name

Tags: query, filter

- [x] Clicking the location edit button will open a modal dialogue with map view
- [x] A User can fully type 'London' and press enter
- [x] The modal dialogue will close and the The location query parameter will be set

## Filter Location by map region

Tags: query, filter

- [x] Clicking the location edit button will open a modal dialogue with map view
- [x] A User can preview map segmentation of 'Countries'
- [x] A User can preview map segmentation of 'Local authorities'
- [x] A User can preview map segmentation of 'Regions of England'
- [x] A User can preview map segmentation of 'Counties of England'
- [x] Hover over a map segment will display a tooltip value
- [x] Clicking a map segment will populate the search term field with tooltip value
- [x] A User can click confirm button
- [x] The modal dialogue will close and the location query parameter will be set

## Date range view - close window

Tags: query, filter, dates

- [x] Clicking the date range edit button will open a modal dialogue with date range fields
- [x] A User can click the close cross icon to close the modal dialogue
- [x] The modal dialogue will close and the date range query parameter will not be set

## Date range view - cancel change

Tags: query, filter, dates

- [x] Clicking the date range edit button will open a modal dialogue with date range fields
- [x] A User can click 'cancel' button to close the modal dialogue
- [x] The modal dialogue will close and the date range query parameter will not be set

## Date range view - select new value

Tags: query, filter, dates

- [x] Clicking the date range edit button will open a modal dialogue with date range fields
- [x] The date range defaults to starting a calendar year from the current previous month
- [x] A User can empty the field input value by clicking the cross icon within field
- [x] A User can select a year and month from the date picker control
- [x] A User can click 'confirm' button
- [x] The modal dialogue will close and the date range query parameter will be set

## invalid date range - empty field

Tags: query, filter, dates

- [x] Clicking the date range edit button will open a modal dialogue with date range fields
- [x] A User can empty the field input value by clicking the cross icon within field
- [x] A User can click 'confirm' button
- [x] The modal dialogue will close and the date range query parameter will inform user an empty field is an 'Invalid date'

## invalid date range - start date after end date

Tags: query, filter, dates

- [x] Clicking the date range edit button will open a modal dialogue with date range fields
- [x] Select 'Mar' and '2021' from the start field
- [x] Select 'Jan' and '2021' from the end field
- [x] A User can click 'confirm' button
- [x] The modal dialogue will show a warning message 'The start date must be earlier than the end date'

**Comment by tomguilbert** [comment]
First section "The page contains multiple links to the applications" - this is a test of UKHPI so there is only a link to UKHPI app, which matches with current production. I guess this has been copied from the script for the HMLR Linked Data landing page, which has links to all 3 apps?

'Hover over a map segment will display a tooltip value' in 7th section: this is not working... @jonrandahl sorry to report possible bug here.

**Comment by jonrandahl** [comment]
@tomguilbert - 'Hover over a map segment will display a tooltip value' in 7th section: this is NOW working ... will resolve [PR](https://github.com/epimorphics/ukhpi/pull/374) in morning!

![Screen Shot 2023-06-14 at 18 29 12 pm  2](https://github.com/epimorphics/hmlr-linked-data/assets/39102/659b207a-b3b7-41e3-9330-31192d9d8a1d)

**Comment by jonrandahl** [comment]
@tomguilbert this is on the [dev instance](https://hmlr-dev-pres.epimorphics.net/app/ukhpi/) for approval

**Comment by tomguilbert** [comment]
Thanks @jonrandahl - this is done 👍
