### ISSUE TITLE
Combined log file improvements for PPD

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/hmlr-linked-data#87]
This issue draws together a number of logging improvements that have been requested. Initially, to keep the scope contained, we will make these changes for PPD, but they will probably be applicable to the other applications as well.

- [x] Log details of requests to data API #85 
- [x] Ensure no non-JSON log messages from entrypoint.sh #82
- [x] Startup and shutdown log messages not emitted as JSON #78 
- [x] PPD not logging to stdout in production #76
- [x] use our own `json-rails-logger` gem

**Comment by ijdickinson** [comment]
done
